package com.tf.ftpserver.model;
// Generated 2018-3-13 16:14:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TStu generated by hbm2java
 */
@Entity
@Table(name = "t_stu", catalog = "test")
public class TStu implements java.io.Serializable {

	private static final long serialVersionUID = -8815067270048534937L;
	private Integer stuid;
	private String stuname;
	private Integer stuage;

	public TStu() {
	}

	public TStu(String stuname, Integer stuage) {
		this.stuname = stuname;
		this.stuage = stuage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stuid", unique = true, nullable = false)
	public Integer getStuid() {
		return this.stuid;
	}

	public void setStuid(Integer stuid) {
		this.stuid = stuid;
	}

	@Column(name = "stuname")
	public String getStuname() {
		return this.stuname;
	}

	public void setStuname(String stuname) {
		this.stuname = stuname;
	}

	@Column(name = "stuage")
	public Integer getStuage() {
		return this.stuage;
	}

	public void setStuage(Integer stuage) {
		this.stuage = stuage;
	}

}
